# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-25 13:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('info', models.CharField(blank=True, max_length=200, null=True)),
                ('polygon', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'polygons',
            },
        ),
    ]
