# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-11 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aba', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='info',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
