# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-13 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_researchquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_id', models.CharField(blank=True, max_length=30, null=True)),
                ('indicator', models.CharField(blank=True, max_length=280, null=True)),
                ('disaggregated_by', models.CharField(blank=True, max_length=280, null=True)),
            ],
            options={
                'db_table': 'indicators',
            },
        ),
        migrations.CreateModel(
            name='IndicatorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_type', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'indicator_types',
            },
        ),
        migrations.AddField(
            model_name='indicator',
            name='indicator_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.IndicatorType'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='research_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.ResearchQuestion'),
        ),
    ]
