# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-17 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20170513_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin4', models.BigIntegerField(blank=True, null=True)),
                ('admin4_name', models.CharField(blank=True, max_length=80, null=True)),
                ('admin1_name', models.CharField(blank=True, max_length=80, null=True)),
                ('admin2_name', models.CharField(blank=True, max_length=80, null=True)),
                ('admin2_type', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'Settlements',
            },
        ),
    ]
