# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-11-01 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_settlements'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABAEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin4', models.BigIntegerField(blank=True, null=True)),
                ('admin4_name', models.CharField(blank=True, max_length=80, null=True)),
                ('admin1_name', models.CharField(blank=True, max_length=80, null=True)),
                ('admin2_name', models.CharField(blank=True, max_length=80, null=True)),
                ('name_KI', models.CharField(blank=True, max_length=80, null=True)),
                ('phone', models.CharField(blank=True, max_length=80, null=True)),
                ('info', models.CharField(blank=True, max_length=500, null=True)),
                ('question', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'ABA_Education',
            },
        ),
    ]
